<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php $this->load->view('authentication/includes/head.php'); ?>
<link rel="stylesheet" href="<?php echo base_url('assets/css/style.min.css')?>" />
<body class="login_admin"<?php if(is_rtl()){ echo ' dir="rtl"'; } ?>>
<style>
    .alert-danger {
        color: #fc2d42;
    }
    .authentication-form{
        width: 472px;
        margin: 0 auto;
    }
    .btn-block{
        padding: 10px;
    }
    ol li {
      margin-top: 10px;
    }
</style>
 <div class="container">
  <div class="row">
   <div class="col-md-4 col-md-offset-4 col-sm-8 col-sm-offset-2 authentication-form-wrapper">
    <div class="company-logo1">
      <?php //get_company_logo(); ?>
    </div>
    <div class="mtop40 authentication-form">
      <h1 style="margin-bottom:20px;"><?php echo _l('Register Device With Google Authenticator'); ?></h1>
      
      <ol>
        <li>Search for "Google Authenticator" app in your Google play store or Apple app store.</li>
        <li>Open the app.</li>
        <li>Pair the app with your Global Presence CRM account by scanning this bar code.</li>
      
      <?php echo form_open($this->uri->uri_string()); ?>
      <?php echo validation_errors('<div class="alert alert-danger text-center">', '</div>'); ?>
      <div class="form-group mtop15" style="text-align: center;">
        <iframe style="border:none;" width="222px" height="205px" src="<?php echo $qr_code_url; ?>"></iframe>
      </div>
      <li>Check for GP CRM in your "Google Authenticator" app for code.</li>
      <li>Verify the pairing was successful by entering a code below.</li>
      <li><a target="_blank" href="https://support.google.com/accounts/answer/1066447?hl=en&co=GENIE.Platform%3DAndroid">Click here</a> for more help.</li>
      </ol>
      
      <div style="text-align: center;">
        <?php echo '<b style="font-weight: 600;">'._l('Code generated by "Google Authenticator" app').'</b>'; ?>
      </div>
      
      <div class="form-group mtop10" style="text-align: center;">
      <?php $this->load->view('authentication/includes/alerts'); ?>
        <!-- <label for="code" class="control-label"><?php //echo _l('Code'); ?></label> -->
        <input type="text" id="code" name="code" class="form-control" autofocus="1" placeholder="Code" style="width: 50%; border-radius: 22px; padding: 0px 22px;">
      </div>

      <input type="hidden" name="secret" value="<?php echo $secret; ?>" />
      
        
       <div class="form-group mtop15" style="text-align: center;;">
        <button type="submit" class="btn btn-info btn-block"><?php echo _l('Next'); ?></button>
      </div>

      <?php echo form_close(); ?>
    </div>
  </div>
</div>
</div>
</body>
</html>
